import { after, test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  GENERATED_MARKER,
  MANAGED_DIRS,
  isGenerated,
  renderClaudeCodeAdapter,
  writeAdapter,
} from "../src/adapter/claude-code.js";
import { COMMAND_TEMPLATES } from "../src/adapter/commands.js";
import { CORE_STAGES } from "../src/config/lifecycle.js";
import { GRAPH_MARKING_STAGES, TRANSIENT_STAGES } from "../src/lifecycle/engine.js";
import { PactwrightError } from "../src/errors.js";
import { resolvePack, type ResolvedPack } from "../src/pack/resolve.js";
import { loadConfig } from "../src/config/config.js";
import { fixture, makeTempProject, repoRoot } from "./helpers.js";

/**
 * sha256 of the complete render of the `complete` pack fixture. Any
 * intentional change to the templates or the fixture pack changes this
 * value: bump it on purpose, in the same commit, after reading the diff.
 */
const COMPLETE_RENDER_HASH =
  "sha256:112587ff33338fee1f70b3f794c128189c815093f5198313626052a24e547e6e";

/**
 * A file shaped as a stale render: frontmatter, then the banner in the
 * position ownership is proved from. A bare marker at byte 0 would not be a
 * render the adapter ever produced, and is deliberately not claimed.
 */
const BANNER = `---\ndescription: gone\n---\n\n${GENERATED_MARKER} from @pactwright/standard@0.0.0 (gone). -->\n\n`;

const FORBIDDEN =
  /\b(supersede the|must supersede|human gate|next stage|advance the lifecycle|mark (the )?(brief|contract|intent) as)\b/i;

const tempDirs: string[] = [];
after(() => {
  for (const dir of tempDirs) fs.rmSync(dir, { recursive: true, force: true });
});

function packAt(dir: string): ResolvedPack {
  const config = loadConfig(path.join(fixture("valid-project"), ".pactwright", "config.yml"));
  const resolved = resolvePack({
    root: dir,
    config: { ...config.value!, agentPack: { source: "./pack" } },
  });
  assert.ok(resolved.value, resolved.problems.map((p) => p.message).join("\n"));
  return resolved.value;
}

function completePack(): ResolvedPack {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  return packAt(dir);
}

function standardPack(): ResolvedPack {
  const config = loadConfig(path.join(fixture("valid-project"), ".pactwright", "config.yml"));
  const resolved = resolvePack({ root: repoRoot, config: config.value! });
  assert.ok(resolved.value, resolved.problems.map((p) => p.message).join("\n"));
  return resolved.value;
}

function hashOf(files: ReadonlyMap<string, string>): string {
  const hash = createHash("sha256");
  for (const [name, content] of files) hash.update(`${name}\n${content}\n`);
  return `sha256:${hash.digest("hex")}`;
}

function treeHashes(root: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const dir of MANAGED_DIRS) {
    for (const entry of fs.readdirSync(path.join(root, dir)).sort()) {
      const content = fs.readFileSync(path.join(root, dir, entry));
      out[`${dir}/${entry}`] = createHash("sha256").update(content).digest("hex");
    }
  }
  return out;
}

test("adapter: rendering the same pack twice is identical, and matches the pinned hash", () => {
  const pack = completePack();
  const first = renderClaudeCodeAdapter(pack);
  const second = renderClaudeCodeAdapter(completePack());
  assert.deepEqual([...first.entries()], [...second.entries()]);
  assert.equal(hashOf(first), COMPLETE_RENDER_HASH);
});

test("adapter: the file set is one agent per pack agent plus the seven commands, sorted", () => {
  const files = renderClaudeCodeAdapter(completePack());
  assert.deepEqual(
    [...files.keys()],
    [
      ".claude/agents/implementer.md",
      ".claude/agents/reviewer.md",
      ".claude/agents/spec.md",
      ...CORE_STAGES.map((stage) => `.claude/commands/${stage}.md`).sort(),
    ],
  );
  assert.equal(COMMAND_TEMPLATES.length, CORE_STAGES.length);
  assert.deepEqual(
    COMMAND_TEMPLATES.map((t) => t.stage),
    [...CORE_STAGES],
  );
});

test("adapter: agent files carry Claude Code frontmatter, the prompt and inlined skills", () => {
  const files = renderClaudeCodeAdapter(completePack());
  const spec = files.get(".claude/agents/spec.md")!;
  assert.match(
    spec,
    /^---\nname: spec\ndescription: '@pactwright\/standard spec — delivery-specification'\n---\n\n/,
  );
  assert.match(
    spec,
    /<!-- Generated by pactwright from @pactwright\/standard@0\.0\.0 \(agents\/spec\.md\)/,
  );
  assert.match(spec, /Fixture prompt for spec\./);
  assert.match(spec, /## Skill: repository-analysis\n/);
  assert.match(spec, /## Skill: contract-writing\n/);
  assert.doesNotMatch(spec, /## Skill: implementation-review/);
  assert.doesNotMatch(spec, new RegExp(repoRoot.replaceAll(path.sep, "\\" + path.sep)));
});

test("adapter: commands invoke the runtime and own no transition rules", () => {
  for (const pack of [completePack(), standardPack()]) {
    const files = renderClaudeCodeAdapter(pack);
    for (const stage of CORE_STAGES) {
      const text = files.get(`.claude/commands/${stage}.md`)!;
      assert.match(text, /^---\ndescription: .+\nargument-hint: .+\n---\n\n/, stage);
      assert.match(text, /pnpm pactwright (context|validate)/, `${stage} asks the runtime`);
      assert.doesNotMatch(text, FORBIDDEN, `${stage} must not state transition rules`);
      assert.doesNotMatch(text, /\$\{/, `${stage} has no unrendered placeholders`);
      if ((GRAPH_MARKING_STAGES as readonly string[]).includes(stage)) {
        assert.match(text, new RegExp(`pnpm pactwright lifecycle record ${stage} --file`), stage);
      } else {
        assert.ok((TRANSIENT_STAGES as readonly string[]).includes(stage));
        assert.doesNotMatch(text, /lifecycle record/, `${stage} records nothing`);
        assert.match(text, /leaves no graph record/, stage);
      }
    }
    for (const [stage, agent] of [
      ["propose-contracts", "spec"],
      ["write-brief", "spec"],
      ["approve-contract", "spec"],
      ["deliver-brief", "implementer"],
      ["prepare-evidence", "implementer"],
      ["review", "reviewer"],
    ] as const) {
      assert.match(
        files.get(`.claude/commands/${stage}.md`)!,
        new RegExp(`Use the \`${agent}\` agent \\(from \`\\.claude/agents/${agent}\\.md\`\\)`),
        `${stage} delegates to ${agent}`,
      );
    }
    for (const agent of files.keys()) {
      if (agent.startsWith(".claude/agents/")) assert.doesNotMatch(files.get(agent)!, FORBIDDEN);
    }
  }
});

test("adapter: ownership is proved by the banner's position, not by mentioning it", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  const write = (name: string, content: string): string => {
    const file = path.join(dir, name);
    fs.writeFileSync(file, content);
    return file;
  };
  const rendered = renderClaudeCodeAdapter(standardPack()).get(".claude/agents/spec.md")!;

  assert.equal(isGenerated(write("real.md", rendered)), true, "a rendered file");
  assert.equal(isGenerated(write("stale.md", `${BANNER}stale\n`)), true, "a stale render");

  // The defect this anchoring exists to close: prose that quotes the banner.
  assert.equal(
    isGenerated(
      write("prose.md", `# Notes\n\nGenerated files open with \`${GENERATED_MARKER} ... -->\`.\n`),
    ),
    false,
    "prose quoting the marker",
  );
  assert.equal(
    isGenerated(write("byte-zero.md", `${GENERATED_MARKER} from nowhere. -->\n\nbody\n`)),
    false,
    "a marker with no frontmatter above it is not a render we produce",
  );
  assert.equal(
    isGenerated(write("after-body.md", `---\na: b\n---\n\n# Title\n\n${GENERATED_MARKER} -->\n`)),
    false,
    "a marker below the first line after the frontmatter",
  );
  assert.equal(isGenerated(write("plain.md", "hand-written\n")), false, "no marker at all");
  assert.equal(isGenerated(path.join(dir, "absent.md")), false, "an unreadable file is kept");
  assert.equal(isGenerated(dir), false, "a directory is kept");
});

test("adapter: a file quoting the banner in prose survives the prune", () => {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  fs.mkdirSync(path.join(dir, ".claude", "commands"), { recursive: true });
  const notes = path.join(dir, ".claude", "commands", "notes.md");
  const content = `# Team notes\n\nOur generated commands open with \`${GENERATED_MARKER} ... -->\`.\n`;
  fs.writeFileSync(notes, content);

  const result = writeAdapter(dir, renderClaudeCodeAdapter(packAt(dir)));
  assert.deepEqual(result.removed, []);
  assert.deepEqual(result.kept, [".claude/commands/notes.md"]);
  assert.equal(fs.readFileSync(notes, "utf8"), content);
});

test("adapter: writing twice is byte-identical, prunes stale generated files and leaves the rest", () => {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  fs.mkdirSync(path.join(dir, ".claude", "commands"), { recursive: true });
  fs.writeFileSync(path.join(dir, ".claude", "commands", "old.md"), `${BANNER}stale\n`);
  fs.writeFileSync(path.join(dir, ".claude", "commands", "mine.md"), "hand-written\n");
  fs.writeFileSync(path.join(dir, ".claude", "settings.local.json"), "{}\n");

  const pack = packAt(dir);
  const first = writeAdapter(dir, renderClaudeCodeAdapter(pack));
  assert.deepEqual(first.removed, [".claude/commands/old.md"]);
  assert.deepEqual(first.kept, [".claude/commands/mine.md"]);
  assert.deepEqual(first.conflicts, []);
  assert.equal(first.written.length, 10);
  const afterFirst = treeHashes(dir);
  const second = writeAdapter(dir, renderClaudeCodeAdapter(pack));
  assert.deepEqual(second.removed, []);
  assert.deepEqual(second.kept, [".claude/commands/mine.md"]);
  assert.deepEqual(treeHashes(dir), afterFirst);
  // The 10 rendered files plus the hand-written one the adapter left alone.
  assert.equal(Object.keys(afterFirst).length, 11);
  assert.equal(fs.readFileSync(path.join(dir, ".claude", "settings.local.json"), "utf8"), "{}\n");
  assert.equal(
    fs.readFileSync(path.join(dir, ".claude", "commands", "mine.md"), "utf8"),
    "hand-written\n",
  );
  assert.ok(!fs.existsSync(path.join(dir, ".claude", "commands", "old.md")));
  for (const entry of fs.readdirSync(path.join(dir, ".claude", "agents"))) {
    assert.doesNotMatch(entry, /\.tmp-/);
  }
});

test("adapter: an unmarked file at a rendered path is reported, not overwritten", () => {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  const mine = path.join(dir, ".claude", "agents", "spec.md");
  fs.mkdirSync(path.dirname(mine), { recursive: true });
  fs.writeFileSync(mine, "my own spec agent\n");

  const result = writeAdapter(dir, renderClaudeCodeAdapter(packAt(dir)));
  assert.deepEqual(result.conflicts, [".claude/agents/spec.md"]);
  assert.equal(result.written.includes(".claude/agents/spec.md"), false);
  assert.equal(result.written.length, 9);
  // A conflicting path is reported once, as a conflict — never also as kept.
  assert.deepEqual(result.kept, []);
  assert.deepEqual(result.removed, []);
  assert.equal(fs.readFileSync(mine, "utf8"), "my own spec agent\n");
});

test("adapter: refuses to write outside the managed directories", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  assert.throws(
    () => writeAdapter(dir, new Map([[".claude/settings.json", "{}"]])),
    /outside the managed adapter directories/,
  );
  assert.ok(!fs.existsSync(path.join(dir, ".claude", "settings.json")));
});

test("adapter: refuses path traversal out of the managed directories", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  for (const key of [
    ".claude/agents/../../x.md",
    ".claude/commands/../settings.json",
    ".claude/agents",
    "/etc/passwd.md",
  ]) {
    assert.throws(
      () => writeAdapter(dir, new Map([[key, "boom"]])),
      (error: unknown) => error instanceof PactwrightError && error.code === "unmanaged-path",
      `expected "${key}" to be refused`,
    );
  }
  assert.ok(!fs.existsSync(path.join(dir, "x.md")));
  assert.ok(!fs.existsSync(path.join(dir, ".claude", "settings.json")));
});

test("adapter: non-canonical keys write and prune under one canonical spelling", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  const first = writeAdapter(dir, new Map([[".claude/agents//a.md", "content\n"]]));
  assert.deepEqual(first.written, [".claude/agents/a.md"]);
  assert.equal(fs.readFileSync(path.join(dir, ".claude", "agents", "a.md"), "utf8"), "content\n");
  const second = writeAdapter(dir, new Map([[".claude/agents/a.md", "content\n"]]));
  assert.deepEqual(second.removed, []);
  assert.throws(
    () =>
      writeAdapter(
        dir,
        new Map([
          [".claude/agents/a.md", "one\n"],
          [".claude/agents//a.md", "two\n"],
        ]),
      ),
    (error: unknown) => error instanceof PactwrightError && error.code === "duplicate-render-path",
  );
});

test("adapter: a failed rename cleans up remaining temps", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  // A directory occupying a target path makes renameSync throw mid-loop.
  fs.mkdirSync(path.join(dir, ".claude", "agents", "blocked.md"), { recursive: true });
  assert.throws(() =>
    writeAdapter(
      dir,
      new Map([
        [".claude/agents/blocked.md", "one\n"],
        [".claude/agents/other.md", "two\n"],
      ]),
    ),
  );
  for (const managed of MANAGED_DIRS) {
    const absolute = path.join(dir, managed);
    if (!fs.existsSync(absolute)) continue;
    for (const entry of fs.readdirSync(absolute)) {
      assert.doesNotMatch(entry, /\.tmp-/);
    }
  }
});
