import { after, test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { MANAGED_DIRS, renderClaudeCodeAdapter, writeAdapter } from "../src/adapter/claude-code.js";
import { COMMAND_TEMPLATES } from "../src/adapter/commands.js";
import { CORE_STAGES } from "../src/config/lifecycle.js";
import { GRAPH_MARKING_STAGES, TRANSIENT_STAGES } from "../src/lifecycle/engine.js";
import { resolvePack, type ResolvedPack } from "../src/pack/resolve.js";
import { loadConfig } from "../src/config/config.js";
import { fixture, makeTempProject, repoRoot } from "./helpers.js";

/**
 * sha256 of the complete render of the `complete` pack fixture. Any
 * intentional change to the templates or the fixture pack changes this
 * value: bump it on purpose, in the same commit, after reading the diff.
 */
const COMPLETE_RENDER_HASH =
  "sha256:637f1b928cd3e5431850c2449dbe7bf344c713253cc588722bc4a78e6f416508";

const FORBIDDEN =
  /\b(supersede the|must supersede|human gate|next stage|advance the lifecycle|mark (the )?(brief|contract|intent) as)\b/i;

const tempDirs: string[] = [];
after(() => {
  for (const dir of tempDirs) fs.rmSync(dir, { recursive: true, force: true });
});

function packAt(dir: string): ResolvedPack {
  const config = loadConfig(path.join(fixture("valid-project"), ".pactwright", "config.yml"));
  const resolved = resolvePack({
    root: dir,
    config: { ...config.value!, agentPack: { source: "./pack" } },
  });
  assert.ok(resolved.value, resolved.problems.map((p) => p.message).join("\n"));
  return resolved.value;
}

function completePack(): ResolvedPack {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  return packAt(dir);
}

function standardPack(): ResolvedPack {
  const config = loadConfig(path.join(fixture("valid-project"), ".pactwright", "config.yml"));
  const resolved = resolvePack({ root: repoRoot, config: config.value! });
  assert.ok(resolved.value, resolved.problems.map((p) => p.message).join("\n"));
  return resolved.value;
}

function hashOf(files: ReadonlyMap<string, string>): string {
  const hash = createHash("sha256");
  for (const [name, content] of files) hash.update(`${name}\n${content}\n`);
  return `sha256:${hash.digest("hex")}`;
}

function treeHashes(root: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const dir of MANAGED_DIRS) {
    for (const entry of fs.readdirSync(path.join(root, dir)).sort()) {
      const content = fs.readFileSync(path.join(root, dir, entry));
      out[`${dir}/${entry}`] = createHash("sha256").update(content).digest("hex");
    }
  }
  return out;
}

test("adapter: rendering the same pack twice is identical, and matches the pinned hash", () => {
  const pack = completePack();
  const first = renderClaudeCodeAdapter(pack);
  const second = renderClaudeCodeAdapter(completePack());
  assert.deepEqual([...first.entries()], [...second.entries()]);
  assert.equal(hashOf(first), COMPLETE_RENDER_HASH);
});

test("adapter: the file set is one agent per pack agent plus the seven commands, sorted", () => {
  const files = renderClaudeCodeAdapter(completePack());
  assert.deepEqual(
    [...files.keys()],
    [
      ".claude/agents/implementer.md",
      ".claude/agents/reviewer.md",
      ".claude/agents/spec.md",
      ...CORE_STAGES.map((stage) => `.claude/commands/${stage}.md`).sort(),
    ],
  );
  assert.equal(COMMAND_TEMPLATES.length, CORE_STAGES.length);
  assert.deepEqual(
    COMMAND_TEMPLATES.map((t) => t.stage),
    [...CORE_STAGES],
  );
});

test("adapter: agent files carry Claude Code frontmatter, the prompt and inlined skills", () => {
  const files = renderClaudeCodeAdapter(completePack());
  const spec = files.get(".claude/agents/spec.md")!;
  assert.match(
    spec,
    /^---\nname: spec\ndescription: '@pactwright\/standard spec — delivery-specification'\n---\n\n/,
  );
  assert.match(
    spec,
    /<!-- Generated by pactwright from @pactwright\/standard@0\.0\.0 \(agents\/spec\.md\)/,
  );
  assert.match(spec, /Fixture prompt for spec\./);
  assert.match(spec, /## Skill: repository-analysis\n/);
  assert.match(spec, /## Skill: contract-writing\n/);
  assert.doesNotMatch(spec, /## Skill: implementation-review/);
  assert.doesNotMatch(spec, new RegExp(repoRoot.replaceAll(path.sep, "\\" + path.sep)));
});

test("adapter: commands invoke the runtime and own no transition rules", () => {
  for (const pack of [completePack(), standardPack()]) {
    const files = renderClaudeCodeAdapter(pack);
    for (const stage of CORE_STAGES) {
      const text = files.get(`.claude/commands/${stage}.md`)!;
      assert.match(text, /^---\ndescription: .+\nargument-hint: .+\n---\n\n/, stage);
      assert.match(text, /pnpm pactwright (context|validate)/, `${stage} asks the runtime`);
      assert.doesNotMatch(text, FORBIDDEN, `${stage} must not state transition rules`);
      assert.doesNotMatch(text, /\$\{/, `${stage} has no unrendered placeholders`);
      if ((GRAPH_MARKING_STAGES as readonly string[]).includes(stage)) {
        assert.match(text, new RegExp(`pnpm pactwright lifecycle record ${stage} --file`), stage);
      } else {
        assert.ok((TRANSIENT_STAGES as readonly string[]).includes(stage));
        assert.doesNotMatch(text, /lifecycle record/, `${stage} records nothing`);
        assert.match(text, /leaves no graph record/, stage);
      }
    }
    for (const [stage, agent] of [
      ["propose-contracts", "spec"],
      ["write-brief", "spec"],
      ["approve-contract", "spec"],
      ["deliver-brief", "implementer"],
      ["prepare-evidence", "implementer"],
      ["review", "reviewer"],
    ] as const) {
      assert.match(
        files.get(`.claude/commands/${stage}.md`)!,
        new RegExp(`Use the \`${agent}\` agent \\(from \`\\.claude/agents/${agent}\\.md\`\\)`),
        `${stage} delegates to ${agent}`,
      );
    }
    for (const agent of files.keys()) {
      if (agent.startsWith(".claude/agents/")) assert.doesNotMatch(files.get(agent)!, FORBIDDEN);
    }
  }
});

test("adapter: writing twice is byte-identical, prunes stale managed files and leaves the rest", () => {
  const dir = makeTempProject({ pack: "complete" });
  tempDirs.push(dir);
  fs.mkdirSync(path.join(dir, ".claude", "commands"), { recursive: true });
  fs.writeFileSync(path.join(dir, ".claude", "commands", "old.md"), "stale\n");
  fs.writeFileSync(path.join(dir, ".claude", "settings.local.json"), "{}\n");

  const pack = packAt(dir);
  const first = writeAdapter(dir, renderClaudeCodeAdapter(pack));
  assert.deepEqual(first.removed, [".claude/commands/old.md"]);
  assert.equal(first.written.length, 10);
  const afterFirst = treeHashes(dir);
  const second = writeAdapter(dir, renderClaudeCodeAdapter(pack));
  assert.deepEqual(second.removed, []);
  assert.deepEqual(treeHashes(dir), afterFirst);
  assert.equal(Object.keys(afterFirst).length, 10);
  assert.equal(fs.readFileSync(path.join(dir, ".claude", "settings.local.json"), "utf8"), "{}\n");
  assert.ok(!fs.existsSync(path.join(dir, ".claude", "commands", "old.md")));
  for (const entry of fs.readdirSync(path.join(dir, ".claude", "agents"))) {
    assert.doesNotMatch(entry, /\.tmp-/);
  }
});

test("adapter: refuses to write outside the managed directories", () => {
  const dir = makeTempProject();
  tempDirs.push(dir);
  assert.throws(
    () => writeAdapter(dir, new Map([[".claude/settings.json", "{}"]])),
    /outside the managed adapter directories/,
  );
  assert.ok(!fs.existsSync(path.join(dir, ".claude", "settings.json")));
});
