import { after, test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { MANAGED_DIRS } from "../src/adapter/claude-code.js";
import { syncProject } from "../src/sync.js";
import { makeTempProject } from "./helpers.js";

const dirs: string[] = [];
after(() => {
  for (const dir of dirs) fs.rmSync(dir, { recursive: true, force: true });
});
function temp(options: Parameters<typeof makeTempProject>[0] = {}): string {
  const dir = makeTempProject(options);
  dirs.push(dir);
  return dir;
}

/** sha256 of every file inside the managed directories, keyed by relative path. */
function treeHashes(root: string): Record<string, string> {
  const hashes: Record<string, string> = {};
  for (const dir of MANAGED_DIRS) {
    const absolute = path.join(root, dir);
    if (!fs.existsSync(absolute)) continue;
    for (const entry of fs.readdirSync(absolute).sort()) {
      const content = fs.readFileSync(path.join(absolute, entry));
      hashes[`${dir}/${entry}`] = createHash("sha256").update(content).digest("hex");
    }
  }
  return hashes;
}

const RENDERED = [
  ".claude/agents/implementer.md",
  ".claude/agents/reviewer.md",
  ".claude/agents/spec.md",
  ".claude/commands/approve-contract.md",
  ".claude/commands/capture-intent.md",
  ".claude/commands/deliver-brief.md",
  ".claude/commands/prepare-evidence.md",
  ".claude/commands/propose-contracts.md",
  ".claude/commands/review.md",
  ".claude/commands/write-brief.md",
];

test("sync: renders the full adapter surface from config + lock", () => {
  const root = temp({ pack: "complete" });
  const report = syncProject(root);
  assert.equal(report.ok, true, report.problems.map((p) => p.message).join("\n"));
  assert.deepEqual(report.changed, RENDERED);
  assert.deepEqual(report.unchanged, []);
  assert.deepEqual(report.removed, []);
  const agent = fs.readFileSync(path.join(root, ".claude", "agents", "spec.md"), "utf8");
  assert.match(agent, /Generated by pactwright .* Do not edit; run `pactwright sync`\./);
});

test("sync: a second run with unchanged inputs is byte-identical and all unchanged", () => {
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const before = treeHashes(root);
  const again = syncProject(root);
  assert.equal(again.ok, true);
  assert.deepEqual(again.changed, []);
  assert.deepEqual(again.unchanged, RENDERED);
  assert.deepEqual(again.removed, []);
  assert.deepEqual(treeHashes(root), before);
});

test("sync: prunes stale managed files and never touches user-authored files", () => {
  const root = temp({ pack: "complete" });
  const userFiles = new Map([
    [".claude/settings.local.json", "{}\n"],
    [".github/workflows/ci.yml", "name: ci\n"],
    ["README.md", "# mine\n"],
  ]);
  for (const [relPath, content] of userFiles) {
    fs.mkdirSync(path.dirname(path.join(root, relPath)), { recursive: true });
    fs.writeFileSync(path.join(root, relPath), content);
  }
  fs.mkdirSync(path.join(root, ".claude", "commands"), { recursive: true });
  fs.writeFileSync(path.join(root, ".claude", "commands", "old.md"), "stale\n");

  const report = syncProject(root);
  assert.equal(report.ok, true);
  assert.deepEqual(report.removed, [".claude/commands/old.md"]);
  assert.equal(fs.existsSync(path.join(root, ".claude", "commands", "old.md")), false);
  for (const [relPath, content] of userFiles) {
    assert.equal(fs.readFileSync(path.join(root, relPath), "utf8"), content);
  }
});

test("sync: an incomplete pack fails without writing", () => {
  const root = temp({ pack: "incomplete" });
  const report = syncProject(root);
  assert.equal(report.ok, false);
  assert.ok(report.problems.some((p) => p.code === "missing-capability"));
  assert.deepEqual(treeHashes(root), {});
});

test("sync: the capability union of enabled extensions gates the render", () => {
  const satisfied = temp({ pack: "extra-capability", extensions: ["fixture-analysis"] });
  const ok = syncProject(satisfied);
  assert.equal(ok.ok, true, ok.problems.map((p) => p.message).join("\n"));

  const unsatisfied = temp({ extensions: ["fixture-analysis"] });
  const failed = syncProject(unsatisfied);
  assert.equal(failed.ok, false);
  assert.match(failed.problems.map((p) => p.message).join("\n"), /operations-analysis/);
  assert.deepEqual(treeHashes(unsatisfied), {});
});

test("sync: an unloadable project is reported, not thrown, and nothing is written", () => {
  const root = temp();
  fs.writeFileSync(path.join(root, ".pactwright", "config.yml"), "version: []\n");
  const report = syncProject(root);
  assert.equal(report.ok, false);
  assert.ok(report.problems.length > 0);
  assert.deepEqual(treeHashes(root), {});
});
