import { after, test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { GENERATED_MARKER, MANAGED_DIRS } from "../src/adapter/claude-code.js";
import { syncProject } from "../src/sync.js";
import { makeTempProject } from "./helpers.js";

/** A file shaped as a stale render: frontmatter, then the banner. */
const BANNER = `---\ndescription: gone\n---\n\n${GENERATED_MARKER} from @pactwright/standard@0.0.0 (gone). -->\n\n`;

const dirs: string[] = [];
after(() => {
  for (const dir of dirs) fs.rmSync(dir, { recursive: true, force: true });
});
function temp(options: Parameters<typeof makeTempProject>[0] = {}): string {
  const dir = makeTempProject(options);
  dirs.push(dir);
  return dir;
}

/** sha256 of every file inside the managed directories, keyed by relative path. */
function treeHashes(root: string): Record<string, string> {
  const hashes: Record<string, string> = {};
  for (const dir of MANAGED_DIRS) {
    const absolute = path.join(root, dir);
    if (!fs.existsSync(absolute)) continue;
    for (const entry of fs.readdirSync(absolute).sort()) {
      const content = fs.readFileSync(path.join(absolute, entry));
      hashes[`${dir}/${entry}`] = createHash("sha256").update(content).digest("hex");
    }
  }
  return hashes;
}

const RENDERED = [
  ".claude/agents/implementer.md",
  ".claude/agents/reviewer.md",
  ".claude/agents/spec.md",
  ".claude/commands/approve-contract.md",
  ".claude/commands/capture-intent.md",
  ".claude/commands/deliver-brief.md",
  ".claude/commands/prepare-evidence.md",
  ".claude/commands/propose-contracts.md",
  ".claude/commands/review.md",
  ".claude/commands/write-brief.md",
];

test("sync: renders the full adapter surface from config + lock", () => {
  const root = temp({ pack: "complete" });
  const report = syncProject(root);
  assert.equal(report.ok, true, report.problems.map((p) => p.message).join("\n"));
  assert.deepEqual(report.changed, RENDERED);
  assert.deepEqual(report.unchanged, []);
  assert.deepEqual(report.removed, []);
  const agent = fs.readFileSync(path.join(root, ".claude", "agents", "spec.md"), "utf8");
  assert.match(agent, /Generated by pactwright .* Do not edit; run `pactwright sync`,/);
  assert.match(agent, /Delete this line to take ownership\./);
});

test("sync: a second run with unchanged inputs is byte-identical and all unchanged", () => {
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const before = treeHashes(root);
  const again = syncProject(root);
  assert.equal(again.ok, true);
  assert.deepEqual(again.changed, []);
  assert.deepEqual(again.unchanged, RENDERED);
  assert.deepEqual(again.removed, []);
  assert.deepEqual(treeHashes(root), before);
});

test("sync: prunes stale generated files and never touches user-authored files", () => {
  const root = temp({ pack: "complete" });
  const userFiles = new Map([
    [".claude/settings.local.json", "{}\n"],
    [".github/workflows/ci.yml", "name: ci\n"],
    ["README.md", "# mine\n"],
    // Inside the managed directories, and therefore the case that matters:
    // location alone must never make a file Pactwright's.
    [".claude/agents/my-db-expert.md", "my own agent\n"],
    [".claude/commands/deploy.md", "my own command\n"],
  ]);
  for (const [relPath, content] of userFiles) {
    fs.mkdirSync(path.dirname(path.join(root, relPath)), { recursive: true });
    fs.writeFileSync(path.join(root, relPath), content);
  }
  fs.writeFileSync(path.join(root, ".claude", "commands", "old.md"), `${BANNER}stale\n`);

  const report = syncProject(root);
  assert.equal(report.ok, true, report.problems.map((p) => p.message).join("\n"));
  assert.deepEqual(report.removed, [".claude/commands/old.md"]);
  assert.equal(fs.existsSync(path.join(root, ".claude", "commands", "old.md")), false);
  assert.deepEqual(report.kept, [".claude/agents/my-db-expert.md", ".claude/commands/deploy.md"]);
  assert.deepEqual(report.conflicts, []);
  for (const [relPath, content] of userFiles) {
    assert.equal(fs.readFileSync(path.join(root, relPath), "utf8"), content);
  }
});

test("sync: a copy of a generated file is still Pactwright's until the banner goes", () => {
  // The banner says "Delete this line to take ownership", so copying a
  // command to customise it and leaving the banner in place keeps it
  // Pactwright's — it is removed once the render stops producing that name.
  // Pinned deliberately: it is the documented contract, not an oversight.
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const commands = path.join(root, ".claude", "commands");
  fs.copyFileSync(path.join(commands, "review.md"), path.join(commands, "my-review.md"));
  assert.deepEqual(syncProject(root).removed, [".claude/commands/my-review.md"]);

  // Dropping the banner line is what takes ownership, and then it survives.
  fs.copyFileSync(path.join(commands, "review.md"), path.join(commands, "mine.md"));
  const mine = path.join(commands, "mine.md");
  fs.writeFileSync(
    mine,
    fs
      .readFileSync(mine, "utf8")
      .split("\n")
      .filter((line) => !line.startsWith(GENERATED_MARKER))
      .join("\n"),
  );
  const report = syncProject(root);
  assert.deepEqual(report.removed, []);
  assert.deepEqual(report.kept, [".claude/commands/mine.md"]);
  assert.equal(fs.existsSync(mine), true);
});

test("sync: refuses to overwrite an unmarked file sitting at a rendered path", () => {
  const root = temp({ pack: "complete" });
  const mine = path.join(root, ".claude", "agents", "spec.md");
  fs.mkdirSync(path.dirname(mine), { recursive: true });
  fs.writeFileSync(mine, "my own spec agent\n");

  const report = syncProject(root);
  assert.equal(report.ok, false);
  assert.deepEqual(report.conflicts, [".claude/agents/spec.md"]);
  assert.deepEqual(
    report.problems.map((p) => p.code),
    ["unmanaged-conflict"],
  );
  assert.equal(fs.readFileSync(mine, "utf8"), "my own spec agent\n");
  assert.equal(report.changed.includes(".claude/agents/spec.md"), false);
  // Every other rendered file still lands, so the surface converges as far
  // as it safely can.
  assert.equal(report.changed.length, RENDERED.length - 1);
});

test("sync: an incomplete pack fails without writing", () => {
  const root = temp({ pack: "incomplete" });
  const report = syncProject(root);
  assert.equal(report.ok, false);
  assert.ok(report.problems.some((p) => p.code === "missing-capability"));
  assert.deepEqual(treeHashes(root), {});
});

test("sync: the capability union of enabled extensions gates the render", () => {
  const satisfied = temp({ pack: "extra-capability", extensions: ["fixture-analysis"] });
  const ok = syncProject(satisfied);
  assert.equal(ok.ok, true, ok.problems.map((p) => p.message).join("\n"));

  const unsatisfied = temp({ extensions: ["fixture-analysis"] });
  const failed = syncProject(unsatisfied);
  assert.equal(failed.ok, false);
  assert.match(failed.problems.map((p) => p.message).join("\n"), /operations-analysis/);
  assert.deepEqual(treeHashes(unsatisfied), {});
});

test("sync: an unloadable project is reported, not thrown, and nothing is written", () => {
  const root = temp();
  fs.writeFileSync(path.join(root, ".pactwright", "config.yml"), "version: []\n");
  const report = syncProject(root);
  assert.equal(report.ok, false);
  assert.ok(report.problems.length > 0);
  assert.deepEqual(treeHashes(root), {});
});
