import { after, test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  applyEnvironmentPlan,
  managedSet,
  planEnvironmentChange,
  type PackageInstaller,
} from "../src/environment/transaction.js";
import { selectTarget } from "../src/environment/select-target.js";
import { useAgentPack } from "../src/pack/select.js";
import { syncProject } from "../src/sync.js";
import { upgradeRuntime, type Reentry } from "../src/upgrade.js";
import { makeTempProject, repoRoot } from "./helpers.js";

/**
 * One environment transaction (consolidation design §6).
 *
 * Four private snapshot routines owned four different file sets, and the
 * render owned none. What these pin is the single managed set, restoration
 * verified rather than asserted, and the one place the writer lock must not
 * be held.
 */

const dirs: string[] = [];
after(() => {
  for (const dir of dirs) fs.rmSync(dir, { recursive: true, force: true });
});

function temp(options: Parameters<typeof makeTempProject>[0] = {}): string {
  const dir = makeTempProject(options);
  dirs.push(dir);
  return dir;
}

/** A project with a declared package manager, which an upgrade requires. */
function consumer(options: Parameters<typeof makeTempProject>[0] = {}): string {
  const dir = temp(options);
  fs.writeFileSync(
    path.join(dir, "package.json"),
    `${JSON.stringify(
      { name: "consumer", private: true, packageManager: "pnpm@11.7.0" },
      null,
      2,
    )}\n`,
  );
  return dir;
}

/** Sorted (path, sha256) pairs for every managed file, absences included. */
function managedDigest(root: string): readonly string[] {
  return managedSet(root).map((file) => {
    if (!fs.existsSync(file)) return `${path.relative(root, file)} <absent>`;
    const hash = createHash("sha256").update(fs.readFileSync(file)).digest("hex");
    return `${path.relative(root, file)} ${hash}`;
  });
}

/* ---- the managed set is one list ---- */

test("transaction: the managed set covers configuration, locks and generated output", () => {
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const relative = managedSet(root).map((file) =>
    path.relative(root, file).split(path.sep).join("/"),
  );

  for (const expected of [
    ".pactwright/config.yml",
    ".pactwright/lifecycle.yml",
    ".pactwright/lock.yml",
    "package.json",
    ".claude/agents/spec.md",
    ".claude/commands/review.md",
  ]) {
    assert.ok(relative.includes(expected), `${expected} must be managed: ${relative.join(", ")}`);
  }
  // The writer lock is not its own subject, and execution state is progress
  // rather than environment (Core §28).
  assert.equal(
    relative.some((file) => file.startsWith(".pactwright/execution/")),
    false,
  );
  assert.equal(relative.includes(".pactwright/.lock"), false);
});

/* ---- restoration is verified, not asserted ---- */

test("transaction: a failed body restores every managed file byte for byte", () => {
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const before = managedDigest(root);

  const plan = planEnvironmentChange(root);
  const { result } = applyEnvironmentPlan(plan, () => {
    // Touch one file of each kind the four old routines disagreed about.
    fs.writeFileSync(path.join(root, ".pactwright", "lock.yml"), "runtime:\n  version: 9.9.9\n");
    fs.writeFileSync(path.join(root, ".claude", "commands", "review.md"), "clobbered\n");
    fs.writeFileSync(path.join(root, "package.json"), "{}\n");
    return { ok: false, value: undefined, problems: [{ code: "nope", message: "refused" }] };
  });

  assert.equal(result.ok, false);
  assert.equal(result.restored, true, JSON.stringify(result.recovery));
  assert.deepEqual(managedDigest(root), before);
});

test("transaction: a file the body creates is removed again, because absence is a state", () => {
  const root = temp({ pack: "complete" });
  const added = path.join(root, ".claude", "commands", "invented.md");
  fs.mkdirSync(path.dirname(added), { recursive: true });

  const plan = planEnvironmentChange(root);
  const { result } = applyEnvironmentPlan(plan, () => {
    fs.writeFileSync(added, "generated by a failed render\n");
    return { ok: false, value: undefined, problems: [{ code: "nope", message: "refused" }] };
  });

  assert.equal(result.restored, true, JSON.stringify(result.recovery));
  assert.equal(fs.existsSync(added), false, "a file that did not exist must not survive a restore");
});

test("transaction: a throw restores too, and does not swallow the error", () => {
  const root = temp({ pack: "complete" });
  const lock = path.join(root, ".pactwright", "lock.yml");
  const before = fs.readFileSync(lock, "utf8");

  assert.throws(
    () =>
      applyEnvironmentPlan(planEnvironmentChange(root), () => {
        fs.writeFileSync(lock, "runtime:\n  version: 9.9.9\n");
        throw new Error("rename failed part-way");
      }),
    /rename failed part-way/,
  );
  assert.equal(fs.readFileSync(lock, "utf8"), before);
});

test("transaction: an install that cannot be undone reports restored false with recovery", () => {
  const root = temp({ pack: "complete" });
  const installed = path.join(root, "node_modules", "left-behind");

  // An installer that installs but cannot undo, which is the case
  // `restored: true` used to claim it had handled: the managed files come
  // back, the package does not, and only re-reading the installed version
  // tells the difference.
  const stubborn: PackageInstaller = ({ spec }) => {
    if (spec === undefined) return [];
    fs.mkdirSync(installed, { recursive: true });
    fs.writeFileSync(
      path.join(installed, "package.json"),
      `${JSON.stringify({ name: "left-behind", version: "1.0.0" })}\n`,
    );
    return [];
  };

  const plan = planEnvironmentChange(root, {
    installs: [{ name: "left-behind", spec: "left-behind@1.0.0" }],
  });
  const { result } = applyEnvironmentPlan(
    plan,
    () => {
      stubborn({ root, manager: "pnpm", spec: "left-behind@1.0.0" });
      return { ok: false, value: undefined, problems: [{ code: "nope", message: "refused" }] };
    },
    { installer: stubborn },
  );

  assert.equal(result.ok, false);
  assert.equal(result.restored, false, "a package left installed is not a restored environment");
  assert.ok(
    result.recovery?.some((line) => line.includes("left-behind")),
    JSON.stringify(result.recovery),
  );
});

/* ---- the writer lock and the runtime re-entry ---- */

test("transaction: a runtime upgrade does not hold the writer lock across re-entry", () => {
  // `cliReentry` runs the new runtime as a *child process*, and the lock's
  // re-entrancy set is per-process (`graph/writer-lock.ts`). If the upgrade
  // held the lock across that spawn, the child would wait its full timeout
  // and then fail with `repository-locked` — so the upgrade is two
  // transactions and the first holds no lock.
  //
  // The re-entry therefore has to be a real child here: an in-process double
  // would take the lock re-entrantly and pass even with the deadlock in
  // place, which is exactly what it did before this was written properly.
  const root = consumer({ pack: "complete" });
  const worker = path.join(root, "reentry.mjs");
  fs.writeFileSync(
    worker,
    [
      `import { withRepositoryLock } from ${JSON.stringify(
        path.join(repoRoot, "src/graph/writer-lock.ts"),
      )};`,
      `withRepositoryLock(process.argv[2], () => {}, { waitMs: 2000 });`,
    ].join("\n"),
    "utf8",
  );

  const install: PackageInstaller = ({ spec }) => {
    if (spec === undefined) return [];
    const dir = path.join(root, "node_modules", "pactwright");
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, "package.json"),
      `${JSON.stringify({ name: "pactwright", version: "9.9.9" })}\n`,
    );
    return [];
  };
  const reenter: Reentry = ({ root: at }) => {
    const child = spawnSync(process.execPath, ["--import", "tsx", worker, at], {
      cwd: repoRoot,
      encoding: "utf8",
    });
    return child.status === 0
      ? []
      : [{ code: "reentry-failed", message: child.stderr.trim() || "no output", path: at }];
  };

  const report = upgradeRuntime(root, { install, reenter });
  assert.equal(report.ok, true, JSON.stringify(report.problems));
});

/* ---- the render is covered too ---- */

test("transaction: a pack switch that fails leaves the generated surface untouched", () => {
  const root = temp({ pack: "complete" });
  assert.equal(syncProject(root).ok, true);
  const before = managedDigest(root);

  // A pack that does not resolve: the switch must not cost the project the
  // environment it had. `useAgentPack` used to snapshot config and lock
  // only, so a failure after `syncProject` left new adapter output beside
  // the old configuration.
  const report = useAgentPack(root, "@pactwright/does-not-exist");
  assert.equal(report.ok, false);
  assert.deepEqual(managedDigest(root), before);
});

/* ---- target selection (R09) ---- */

test("selectTarget: picks the newest version inside the configured range", () => {
  const selected = selectTarget(
    { kind: "agent-pack", name: "@pactwright/standard" },
    "^0.1.0",
    { runtimeVersion: "0.0.2" },
    { manager: "pnpm", view: () => ["0.1.0", "0.1.7", "0.2.0", "1.0.0"] },
  );
  assert.ok(!Array.isArray(selected), JSON.stringify(selected));
  // `^0.1.z` fixes the minor under npm semantics, so 0.2.0 is out of range
  // even though it is newer.
  assert.equal((selected as { version: string }).version, "0.1.7");
});

test("selectTarget: an absent constraint means newest compatible, not `^0.0.0`", () => {
  // There is no range spelling for "any": `^0.0.0` is exact under npm caret
  // semantics, so it would select 0.0.0 and nothing else.
  const selected = selectTarget(
    { kind: "extension", name: "@pactwright/fixture-base" },
    undefined,
    { runtimeVersion: "0.0.2" },
    { manager: "pnpm", view: () => ["0.0.0", "0.1.0", "0.2.3"] },
  );
  assert.ok(!Array.isArray(selected));
  assert.equal((selected as { version: string }).version, "0.2.3");
});

test("selectTarget: skips versions the running runtime cannot satisfy", () => {
  const selected = selectTarget(
    { kind: "extension", name: "@pactwright/fixture-base" },
    undefined,
    {
      runtimeVersion: "0.0.2",
      declaredRuntimeRange: (version) => (version === "2.0.0" ? "^9.0.0" : "0.0.2"),
    },
    { manager: "pnpm", view: () => ["1.0.0", "2.0.0"] },
  );
  assert.ok(!Array.isArray(selected));
  assert.equal((selected as { version: string }).version, "1.0.0");
  assert.deepEqual((selected as { rejected: readonly string[] }).rejected, ["2.0.0"]);
});

test("selectTarget: reports rather than guesses when nothing fits", () => {
  const none = selectTarget(
    { kind: "runtime", name: "pactwright" },
    "^3.0.0",
    { runtimeVersion: "0.0.2" },
    { manager: "pnpm", view: () => ["0.0.1", "0.0.2"] },
  );
  assert.ok(Array.isArray(none));
  assert.equal((none as readonly { code: string }[])[0]?.code, "no-version-in-range");

  const incompatible = selectTarget(
    { kind: "extension", name: "@pactwright/fixture-base" },
    undefined,
    { runtimeVersion: "0.0.2", declaredRuntimeRange: () => "^9.0.0" },
    { manager: "pnpm", view: () => ["1.0.0"] },
  );
  assert.ok(Array.isArray(incompatible));
  assert.equal((incompatible as readonly { code: string }[])[0]?.code, "incompatible-target");
});

test("selectTarget: a view that fails is reported, not treated as an empty registry", () => {
  const result = selectTarget(
    { kind: "runtime", name: "pactwright" },
    undefined,
    { runtimeVersion: "0.0.2" },
    { manager: "pnpm", view: () => [{ code: "package-view-failed", message: "offline" }] },
  );
  assert.ok(Array.isArray(result));
  assert.equal((result as readonly { code: string }[])[0]?.code, "package-view-failed");
});
