/**
 * A2-D probe 08 — every writer: init, sync ownership, remove/re-add, and
 * what the transaction's restore sweep is allowed to delete.
 *
 * Most of this is a positive control. A reimplementation that discards these
 * behaviours because nobody recorded that they worked would be worse than
 * one that keeps a known flaw.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { initProject } from "../../../src/init.js";
import { syncProject } from "../../../src/sync.js";
import { writeAdapter } from "../../../src/adapter/claude-code.js";
import { addExtension, removeExtension } from "../../../src/extension/manage.js";
import {
  applyEnvironmentPlan,
  planEnvironmentChange,
} from "../../../src/environment/transaction.js";
import { useAgentPack } from "../../../src/pack/select.js";
import { runtimeVersion } from "../../../src/version.js";
import { cleanup, makeProject, report, write } from "./fixture.js";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";

const RUNTIME = runtimeVersion();

/* 1 — init: idempotence, scaffold honesty, refusal to default a pack. ----- */
{
  const root = mkdtempSync(join(tmpdir(), "a2d-init-"));
  const first = initProject(root);
  const second = initProject(root);
  const withNoPack = initProject(root, { withExtensions: ["fixture-base"] });
  report("init", {
    firstRun: {
      ok: first.ok,
      scaffold: first.scaffold === true,
      created: first.entries.filter((e) => e.action === "created").map((e) => e.path),
    },
    secondRun: {
      ok: second.ok,
      everythingSkipped: second.entries.every((e) => e.action === "skipped"),
    },
    lockWrittenForAScaffold: existsSync(join(root, ".pactwright", "lock.yml")),
    withExtensionsButNoPack: {
      ok: withNoPack.ok,
      problems: withNoPack.problems.map((p) => p.code),
    },
  });
  rmSync(root, { recursive: true, force: true });
}

/* 2 — sync: determinism, ownership, pruning. ------------------------------ */
{
  const root = makeProject({
    pack: { name: "@probe/pack", version: "0.1.0", pactwright: RUNTIME },
    packageManager: "pnpm@11.7.0",
    runtime: RUNTIME,
  });
  useAgentPack(root, "@probe/pack");
  const a = syncProject(root);
  const b = syncProject(root);
  report("sync is deterministic", {
    firstChanged: a.changed.length,
    secondChanged: b.changed.length,
    secondUnchanged: b.unchanged.length,
    ok: a.ok && b.ok,
  });

  // A user file at a rendered path, with no banner.
  const rendered = join(root, ".claude", "commands", "review.md");
  writeFileSync(rendered, "# mine\n\nHand written, no frontmatter, no banner.\n", "utf8");
  // A user file that quotes the banner in its prose, at a non-rendered path.
  writeFileSync(
    join(root, ".claude", "commands", "notes.md"),
    "# notes\n\nOur docs mention <!-- Generated by pactwright ... --> in passing.\n",
    "utf8",
  );
  // A generated file the render no longer produces.
  const orphan = join(root, ".claude", "agents", "gone.md");
  writeFileSync(
    orphan,
    "---\nname: gone\n---\n\n<!-- Generated by pactwright from x -->\n\nstale\n",
    "utf8",
  );

  const c = syncProject(root);
  report("sync against user state", {
    ok: c.ok,
    conflicts: c.conflicts,
    kept: c.kept,
    removed: c.removed,
    conflictingFileUntouched: readFileSync(rendered, "utf8").startsWith("# mine"),
    otherRenderedFilesStillLanded: existsSync(join(root, ".claude", "commands", "write-brief.md")),
    problems: c.problems.map((p) => p.code),
  });

  // Writing outside the managed directories.
  let escaped: string;
  try {
    writeAdapter(root, new Map([[".claude/agents/../../escape.md", "x"]]));
    escaped = "WROTE OUTSIDE THE MANAGED DIRECTORIES";
  } catch (error) {
    escaped = `refused: ${(error as Error).message}`;
  }
  report("writeAdapter with a traversal in a rendered key", escaped);

  /* 3 — what the restore sweep deletes. ---------------------------------- */
  const plan = planEnvironmentChange(root);
  applyEnvironmentPlan(plan, () => {
    // A file that appears inside a managed directory while the transaction is
    // open — a second process, an editor, a generator. It has no banner, so
    // `sync` would never touch it.
    writeFileSync(
      join(root, ".claude", "commands", "concurrent.md"),
      "# not pactwright's\n",
      "utf8",
    );
    return { ok: false, value: undefined, problems: [{ code: "probe", message: "injected" }] };
  });
  report("a non-generated file created inside a managed directory during a failing transaction", {
    survivedTheRestore: existsSync(join(root, ".claude", "commands", "concurrent.md")),
    managedDirNow: readdirSync(join(root, ".claude", "commands")).sort(),
  });
  cleanup(root);
}

/* 4 — remove then re-add. ------------------------------------------------- */
{
  const ext = {
    id: "probe-notes",
    pkg: "@probe/notes",
    version: "0.1.0",
    pactwright: RUNTIME,
    graph: ["graph:", "  node_types:", "    note:", "      required_fields: []"].join("\n"),
  };
  const root = makeProject({
    pack: { name: "@probe/pack", version: "0.1.0", pactwright: RUNTIME },
    packageManager: "pnpm@11.7.0",
    runtime: RUNTIME,
    extensions: [ext],
  });
  useAgentPack(root, "@probe/pack");
  write(
    root,
    "specs/nodes/note-probe-cc33.md",
    "---\nid: note-probe-cc33\ntype: note\ntitle: probe note\ncreated: 2026-09-01\n---\n\nUser-authored extension record.\n",
  );
  const lockBefore = readFileSync(join(root, ".pactwright/lock.yml"), "utf8");
  const configBefore = readFileSync(join(root, ".pactwright/config.yml"), "utf8");

  const removed = removeExtension(root, "probe-notes");
  report("extension remove", {
    ok: removed.ok,
    changes: removed.changes,
    preserved: removed.preserved,
    problems: removed.problems.map((p) => p.code),
    recordStillOnDisk: existsSync(join(root, "specs/nodes/note-probe-cc33.md")),
    lockStillNamesIt: /probe-notes/.test(readFileSync(join(root, ".pactwright/lock.yml"), "utf8")),
  });

  const readded = addExtension(root, "@probe/notes", { allowInstall: false });
  report("extension re-add", {
    ok: readded.ok,
    changes: readded.changes,
    problems: readded.problems.map((p) => `${p.code}: ${p.message}`),
    lockIdenticalToBefore: readFileSync(join(root, ".pactwright/lock.yml"), "utf8") === lockBefore,
    configIdenticalToBefore:
      readFileSync(join(root, ".pactwright/config.yml"), "utf8") === configBefore,
    configNow: readFileSync(join(root, ".pactwright/config.yml"), "utf8")
      .split("\n")
      .filter((l) => /probe-notes|enabled|source|extensions/.test(l)),
  });
  cleanup(root);
}

void mkdirSync;
